load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")
load("@fbsource//tools/build_defs:rust_unittest.bzl", "rust_unittest")

oncall("build_infra")

rust_library(
    name = "buck2_bzlmod",
    srcs = glob(["src/**/*.rs"]),
)

rust_unittest(
    name = "buck2_bzlmod_tests",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
)
